services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file:
      - apps/api/.env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    container_name: api
    restart: always
    env_file:
      - apps/api/.env
    ports:
      - '4000:4000'
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    container_name: web
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - api

volumes:
  db_data:
